FROM mysql:8.0.17

MAINTAINER me

ENV MYSQL_DATABASE=supercars \
    MYSQL_ROOT_PASSWORD=AppDynamics

ADD mysql.sql /docker-entrypoint-initdb.d

EXPOSE 3306

ndidate = random.randrange(limit)
        randoms.append(candidate)
    randoms = list(dict.fromkeys(randoms))
    return randoms

def trim_table(selectQuery, deleteQuery, max, toDelete, cnx):
    cursor = cnx.cursor()
    cursor.execute(selectQuery)
    IDs = cursor.fetchall()
    cursor.close()
    
    IDsDeleted = []
